version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/kai_engine"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pub"
  - package-ecosystem: "pub"
    directory: "/packages/kai_engine_firebase_ai"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pub"